# Make sure you have built the example application before running
# May have to run 'docker-compose rm' before 'docker-compose up' to make sure clean containers are used
consulserver:
  image: "progrium/consul"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "53/udp:8600"
  command: -server -bootstrap -ui-dir /ui -advertise 192.168.59.103
registrator:
  image: "progrium/registrator"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  hostname: 192.168.59.103
  command: consul://192.168.59.103:8500
example1:
  image: "reactive-consul-example:0.1-SNAPSHOT"
  ports:
    - "8080"
  environment:
    - SERVICE_NAME=example-service-1
  dns:
    - 172.17.42.1
example2:
  image: "reactive-consul-example:0.1-SNAPSHOT"
  ports:
    - "8080"
  environment:
    - SERVICE_NAME=example-service-2
  dns:
    - 172.17.42.1